window.__CONFIG__ = {
  // url must NOT end with a slash
  VITE_CORS_PROXY_URL: "movie.d-tsarddakas.workers.dev",
  VITE_TMDB_READ_API_KEY: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhNDVlYjY0ZmRjMDdkNzIxMWMyMTU4NWFhMzQ4MTI1MyIsInN1YiI6IjY1NTk1M2JiZWE4NGM3MTA5MTBkOTBkOCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.TeQhaMdHJFNx_6MEKJJJM7VzDdwnP90E0gsDLp10XdQ"
};
